name: task
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  http: ^1.3.0
  infinite_scroll_pagination: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.0
  mobx_codegen: ^2.7.0

flutter:
  uses-material-design: true
